### ISSUE TITLE
QoL- Dynamically name new plots

### ISSUE THREAD

**Issue by cicetil** [Atherys-Horizons/AtherysTowns#100]
**Description:** _What are you proposing?_
When creating a new plot, the default name should be automatically numbered based on how many plots there currently are.
IE. You will have _`"Plot #1", "Plot #2", "Plot #3", etc.`_ as new plots are created.

**Purpose:** _What use-case does this have? Why would we implement it?_
If all plots have the same name when created, it can become difficult to differentiate and organize them.
Having them numbered by default removes the need for players to rename each new plot themselves.

**Comment by codestripper** [comment]
PR closed issue.
