### ISSUE TITLE
Plot Permissions

### ISSUE THREAD

**Issue by InsanibleLector** [Atherys-Horizons/AtherysTowns#113]
Permissions for Plots
- Build
- Destroy
- Damage Non-Players
- Damage Players
- Interact with Doors
- Interact with Redstone
- Interact with Tile Entities
- Interact with Entities
- Spawn Entities

Permissions set as...
Owner
Friend of Owner
Town
Ally of Town and Nation
Public

ex. Plot permission.
Build - Owner, Friend
Destroy - Owner, Friend
Damage Non-Players - Owner
Damage Players - Public
Interact with Doors - Owner, Friend, Town, Ally
Interact with Redstone - Owner, Friend
Interact with Tile Entities - Owner, Friend
Interact with Entities - Owner, Friend
Spawn Entities - Public

**Comment by codestripper** [comment]
Structure:
Database Columns:

- Friend
- Town
- Ally
- Enemy
- Neutral

Each column should contain a Set<WorldPermission> that contains all of the permissions granted to that group.
By default, owner of the plot should have full permissions.

**Comment by cicetil** [comment]
Replace **_Enemy_** with **_Public_** to provide an easy method for granting plot permissions to all players.
The use case for only enemies is very low and a public group would be more beneficial.
