### ISSUE TITLE
Hover-text for tax amount breakdown

### ISSUE THREAD

**Issue by cicetil** [Atherys-Horizons/AtherysTowns#140]
**Description:** _What are you proposing?_
While hovering over the amount of tax owed, you will be shown a breakdown of what makes up that amount.
ie.  Next Tax Payment: **1,100**, hovering over "1,000" would show [ Base: 500 , Resident: 100 , Area: 200 , etc ], similar to the hover-text for attributes 

**Purpose:** _What use-case does this have? Why would we implement it?_
You can currently only see the total tax amount, however it can be very useful for town leaders to understand where the bulk of taxes are coming from and how they can plan around their expenses.

**Comment by AaronFoley** [comment]
Fixed
