### ISSUE TITLE
Admin Command Town Tax Flag

### ISSUE THREAD

**Issue by InsanibleLector** [Atherys-Horizons/AtherysTowns#147]
**Description:** Add a flag for towns to be taxed or not. Allow admins only to toggle this flag true or false. 
False = No Tax 
True = Tax

**Purpose:** Allows setting specialty towns that will always exist.

**Comment by HaedHutner** [comment]
Done with https://github.com/Atherys-Horizons/AtherysTowns/commit/c1ba382b1a1ad7359ce0afbcaf98068519001d3e
