### ISSUE TITLE
Implement Command: /town unclaim

### ISSUE THREAD

**Issue by HaedHutner** [Atherys-Horizons/AtherysTowns#37]
**Syntax:** `/town unclaim`, `/town abandon`

**Description**:
Removes the plot the source player is currently located in from the town and subsequently from existence. Must check if player has permission to do this.

**Comment by LJNIC** [comment]
To add, this is much more complex than it seems at first glance. We will need to make sure that unclaiming the plot won't leave plots stranded (without bordering plots). This will probably require a  complex algorithm.
