### ISSUE TITLE
Roles ( Nation & Town )

### ISSUE THREAD

**Issue by HaedHutner** [Atherys-Horizons/AtherysTowns#71]
It is necessary to group together several permissions so as to ease the promoting and demoting of players within a Town or Nation. These groups of permissions are to be referred to as "Roles".

* There should be 2 different types of roles: `NationRole` and `TownRole`. Both of these should inherit from a common `Role` class.
* `NationRoles` can only be awarded to or revoked from a Resident by the Nation Leader ( or any other Resident with the `add_permission` nation permission ).
* `TownRoles` can only be awarded to or revoked from a Resident by the Town Leader ( or any other Resident with the `add_permission` town permission ).
* `NationRoles` and `TownRoles` should be separate entities stored in the database.

A Resident should have both a list of explicitly given permissions ( the way it works right now ), and a list of `Roles` the Resident belongs to. Explicit permissions override role permissions, and in the event of a conflict will be preferred over the latter.

While stored in the database, `Roles` should be configurable.

There should be 2 different types of configurable Roles, for Towns and Nations, as follows:

```
roles {
    nation-roles [
        {
            id = "leader"
            name = "Leader"
            nation-permissions [
                "deposit",
                "withdraw",
                ...
            ]
        },
        {
            ...
        }
    ]
    town-roles [
        {
            id = "mayor"
            name = "Mayor"
            town-permissions [
                "deposit",
                "withdraw",
                ...
            ],
            world-permissions [
                "build",
                "destroy",
                "damage_entity",
                ...
            ]
        },
        {
            ...
        }
    ]
}
```

**Comment by codestripper** [comment]
Commands:
/town role create <name>
/town role delete <name>
/town role modify <role> remove <permission>
/town role modify <role> add <permission>
/town role grant <player> <role>
/town role revoke <player> <role>

/nation role create <name>
/nation role delete <name>
/nation role modify <role> remove <permission>
/nation role modify <role> add <permission>
/nation role grant <player> <role>
/nation role revoke <player> <role>
